### ISSUE TITLE
using ore'ed strings in package may segfault (??) 

### ISSUE THREAD

**Issue by thomasWeise** [jonclayden/ore#5]
Hi.

First of all, I probably did something wrong.
I am working on a package that also does some text processing using ore's great regular expression support.
I thought I might be clever and store some regular expressions not just as text string, but as `ore` objects created via the `ore` function.
If I do so, my package will segfault when applying the objects as regular expression in the check phase, but not if I run the tests directly in RStudio.
I have traced the issue down to using the ore function (segfault when checking the package) or not using the `ore` function (no seg fault).

You can see the difference here

https://travis-ci.org/thomasWeise/bookbuildeR/builds/423887312

vs.

https://travis-ci.org/thomasWeise/bookbuildeR/builds/423878414

Of course, the error is probably just on my side, so this issue might be useless.
My working premise is that I use the function ore wrong or somewhere leak a wrong type into/out of ore.

Nevertheless, even if the error is on my side, maybe the segfault can somehow be prevented and/or turned into a more graceful error message.

Anyway, many thanks for your great library!
Thomas.

Added Note: The error happened seemingly only if the result of `ore` is stored in the variable inside the package.

**Comment by thomasWeise** [comment]
Thank you.
Sorry for my late reply.
Initially, I thought the error could have been somehow caused by the fact that I am storing an ored string in a variable in a package. I thought maybe it has something to do with the way packages are loaded or something... ...but this is because I know very very little about that :-) The testthat hypothesis is much more likely. Anyway, your fix should handle the problem either way.
Again, many thanks for your great package!
It does exactly what I wanted, and it does so through a clear and easy-to-understand API.
Thanks.

**Comment by jonclayden** [comment]
Thanks again for the report. If you see the issue persist with the new code, do let me know. All the best!
