### ISSUE TITLE
Error: this package has a non-empty 'configure.win' file

### ISSUE THREAD

**Issue by N1h1l1sT** [jonclayden/ore#6]
Installation fails on Windows on newest R 3.6.1 with this message:
"this package has a non-empty 'configure.win' file"

It seems to be the same thing as: https://github.com/r-lib/remotes/issues/272
I'm not sure what I can do on my part to get over it and install it.
Over CRAN it gets installed, but only on 64bit, however "ore" 32bit and 64bit is needed for tractor.base, and because only the 64bit gets installed, tractor.base then fails to be installed.

**Comment by jonclayden** [comment]
Thanks for the report. Can you clarify the exact context of this failure please? The [CRAN check logs](https://cran.r-project.org/web/checks/check_results_ore.html) suggest that both 32-bit and 64-bit Windows builds are being created and tested there, for both [R-release](https://www.r-project.org/nosvn/R.check/r-release-windows-ix86+x86_64/ore-00check.html) and [R-devel](https://www.r-project.org/nosvn/R.check/r-devel-windows-ix86+x86_64/ore-00check.html).

**Comment by N1h1l1sT** [comment]
```R
> install.packages("ore", repos = "https://cloud.r-project.org", type = "source")
trying URL 'https://cloud.r-project.org/src/contrib/ore_1.6.2.tar.gz'
Content type 'application/x-gzip' length 432201 bytes (422 KB)
downloaded 422 KB

* installing *source* package 'ore' ...
** package 'ore' correctement décompressé et sommes MD5 vérifiées
** using staged installation
** libs
Warning: this package has a non-empty 'configure.win' file,
so building only the main architecture
```

Then there are like hundreds of lines like this `C:/Rtools/mingw_64/bin/gcc  -I"C:/Users/IOANNI~1.MAM/DOCUME~1/R/R-36~1.1/include" -DNDEBUG -Ionig -Ionig/enc -Ionig/enc/unicode -DUNALIGNED_WORD_ACCESS=0         -O2 -Wall  -std=gnu99 -mtune=generic -c compile.c -o compile.o`

ending in:

```R
installing to C:/Users/Ioannis.MAMALIKIDIS/Documents/R/R-3.6.1/library/00LOCK-ore/00new/ore/libs/x64
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'ore'
    finding HTML links ... fini
    es                                      html  
    matches                                 html  
    ore                                     html  
    ore.dict                                html  
    ore.escape                              html  
    ore.file                                html  
    ore.ismatch                             html  
    ore.lastmatch                           html  
    ore.search                              html  
    ore.split                               html  
    ore.subst                               html  
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (ore)
```
So, if I wanted to use "ore" directly, I can, because it succeeded in installing the 64bit version,
however because of the message it says in the beginning "so building only the main architecture", the 32bit version was never built and installed.

So when I proceed to install packages that depend on ore, like tractor.base, it tells me:
```
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'tractor.base' in library.dynam(lib, package, package.lib):
 DLL 'ore' not found: maybe not installed for this architecture?
Erreur : le chargement a échoué
Exécution arrêtée
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/Ioannis.MAMALIKIDIS/Documents/R/R-3.6.1/library/tractor.base'
Warning in install.packages :
  installation of package ‘tractor.base’ had non-zero exit status
```

**Comment by jonclayden** [comment]
OK, thanks. I’ll try and reproduce this when I can get onto a Windows machine.

**Comment by jonclayden** [comment]
The latest commit to `master` seems to fix this on my test machine. If you could confirm that it works for you too, I'll get a new release out with this issue resolved.

**Comment by N1h1l1sT** [comment]
I can confirm that the issue is fixed.
I installed via install_github("jonclayden/ore") and both architectures were build successfully

Thank you 👍
